// APP ACTIONS
export const APP_RENDERED_ON_CLIENT = "APP_RENDERED_ON_CLIENT";

// INPUT ACTIONS
export const ENTER_CHARACTER = "ENTER_CHARACTER";
export const KEY_LEFT = "KEY_LEFT";
export const KEY_RIGHT = "KEY_RIGHT";
export const BACKSPACE = "BACKSPACE";
export const ENTER = "ENTER";

// PROGRESS ACTIONS
export const MOVE_TO_NEXT_STAGE = "MOVE_TO_NEXT_STAGE";
export const MOVE_TO_PREVIOUS_STAGE = "MOVE_TO_PREVIOUS_STAGE";
export const STAGE_COMPLETE = "STAGE_COMPLETE";
export const SUBMIT_ANSWER = "SUBMIT_ANSWER";
